blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/rramoscabral/AZ-2008---Training---DevOps-Foundations-The-Core-Principles-and-Practices/discussions
    about: Ask questions and discuss with other community members
